package com.rdani2005.bitstate.domain.valueobject;

public enum UserPermissions {
    RENT_HOUSE,
    BUY_HOUSE,
    ADD_PERSONAL_HOUSE_FOR_RENT,
    ADD_PERSONAL_HOUSE_FOR_SELL,
    DELETE_PERSONAL_HOUSE_FOR_RENT,
    DELETE_PERSONAL_HOUSE_FOR_SELL,
    DELETE_OTHERS_HOUSE_FOR_RENT,
    DELETE_OTHERS_HOUSE_FOR_SELL,
    ADMIN_USERS,
    ADD_ADMIN_USERS,
    DELETE_USERS,
    ADMIN_TRANSACTIONS,
    UNDO_TRANSACTIONS,
}
